apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  selector:
    app: python-app-7985b8794f-d8b9b
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer